### ISSUE TITLE
Should it generate a 350 mb folder?

### ISSUE THREAD

**Issue by AlexanderBlackman** [teobugslayer/AvaloniaCoreRTDemo#35]
I'm not sure what I'm doing wrong

The bat file gives lots of Trim and AoT warnings and produces a massive folder.
[output from  test cmd.txt](https://github.com/teobugslayer/AvaloniaCoreRTDemo/files/15007709/output.from.test.cmd.txt)

**Comment by teobugslayer** [comment]
These are two questions.

1. Yes, it is expected to have a lot of files which take some space. Most of them are temporary files used only during the building process. The final files (which, say, you could give to your users) are in the folder `src\bin\Release\net7.0\win-x64\publish`. The are only 150 MB and 111 MB of these are the debug symbols (the .pdb file) which you can safely ignore, unless you need to debug the Release build. So, essentially the minimal app would be around 41 MB.
2. The trimming warnings are of some concern because they show **potential** issues. The reason for the warning is that Avalonia XAML uses extensively reflection, and AOT **passionately hates** reflection. That's why, when you are building Avalonia-based app with AOT, you need to test it thoroughly and ensure that the reflection works properly. You may need to adjust the `rd.xml` file to make sure the types which are reflected upon are included in the final build. I expect that with time Avalonia and AOT will continue to mature and these warnings will naturally disappear.

**Comment by AlexanderBlackman** [comment]
Thank you for your explanation. I understand now.
